### ISSUE TITLE
其实这个修改版libass还是有bug的。

### ISSUE THREAD

**Issue by eko5624** [dyphire/mpv-winbuild#2]
比如下面这个ass字幕文件，您可以测试一下。没有完全修复这个问题。
https://github.com/dyphire/libass/commit/3c136296d0969dbc906c0155ca0062a5aa200ddc
这个二维码不能正常显示：
<img width="1395" alt="图片" src="https://user-images.githubusercontent.com/84926938/139425143-f8f101da-a53d-4ca4-9805-110bd0e134d5.png">
[Game.of.Thrones.S07E01.Dragonstone.REPACK.1080p.AMZN.WEB-DL.DD+5.1.H.264-GoT.简体&英文.ass.zip](https://github.com/dyphire/mpv-winbuild/files/7441446/Game.of.Thrones.S07E01.Dragonstone.REPACK.1080p.AMZN.WEB-DL.DD%2B5.1.H.264-GoT.ass.zip)

**Comment by eko5624** [comment]
谢谢回复。字幕文件编写不规范确实是个问题。不过好多字幕组制作的字幕确实也没写PlayResX和PlayResY值。potplayer和mpc-be内建字幕处理器却能妥善处理这个问题。只能坐等大佬修复了。这个bug在libass仓库好像提了好几年了，看来是不好修复。。

**Comment by dyphire** [comment]
VSFilter系字幕渲染器在这方面的兼容性上做的是很不错，存在这么多的不规范ass字幕也和它有关。ass字幕制作者使用最多的ass制作工具Aegisub，其字幕渲染器组件默认用的VSFilter，也就导致了VSFilter下看似正常实际不被libass兼容的错误标签行为。

典型例子还有`ScaledBorderAndShadow`这个ass标签缺失时libass和VSFilter对此完全相反的默认缩放行为

**Comment by dyphire** [comment]
@eko5624 https://github.com/dyphire/libass/commit/c75d37f5dd402cf332baaa70e1c2e3a713585a28 修改版使用新方式实现了这一功能，此问题已被修复
![](https://cdn.jsdelivr.net/gh/dyphire/PicGo/img/2022/01/01/20220101144337.png)
代码源自libass开发者 https://github.com/astiob/libass/commit/a550fc5115bd36cb9d0510976d7357b609410645 暂未合并至主分支

**Comment by eko5624** [comment]
赞！赞！赞！终于等到这一天了。。

**Comment by dyphire** [comment]
**友情提醒：自libass此提交https://github.com/libass/libass/commit/f08f8ea522d20dd9985544c636e45e4984a0d743之后已修复这一长达7年之久的bug。最新版已回归libass官方源编译，移除相应修改分支

**Comment by dyphire** [comment]
无法复现，我这边测试正常
![image](https://user-images.githubusercontent.com/61936050/196134062-911e6bee-5411-4312-9696-d075f9fc432a.png)

**Comment by eko5624** [comment]
奇怪了，用shinchiro编译的最新版测试也是一样的问题。

**Comment by dyphire** [comment]
是不是视频比例不一样，我是用16:9的1080p视频测试的
