### ISSUE TITLE
Release中版本很多，该如何选择？

### ISSUE THREAD

**Issue by VimWei** [dyphire/mpv-winbuild#26]
这些版本有什么区别？该如何选择？

1. ffmpeg-x86_64-git-e88992ecb.7z
2. ffmpeg-x86_64-v3-git-048f4e621.7z
3. mpv-dev-x86_64-20240926-git-9d390ef.7z
4. mpv-dev-x86_64-v3-20240926-git-d35c2da.7z
5. mpv-x86_64-20240926-git-9d390ef.7z
6. mpv-x86_64-v3-20240926-git-d35c2da.7z

**Comment by laodaoxp** [comment]
mpv-x86_64-v3-20240926-git-d35c2da.7z

**Comment by VimWei** [comment]
Thanks!
